/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.vista;

import proyecto.controlador.UsuarioController;
import proyecto.modelo.Administrador;
import proyecto.modelo.Empleado;
import proyecto.modelo.JefeDeAbastecimiento;
import proyecto.modelo.Usuario;
import proyecto.util.Mensajes;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import proyecto.controlador.LoginController;

/**
 *
 * @author User0
 */
public class form_AltUsuarios extends javax.swing.JDialog {

    private UsuarioController usuarioController;
    private Usuario userToEdit; // Usuario que se está editando (null si es nuevo)
    private boolean successOperation = false;

    /**
     * Creates new form NewJDialog
     */
    public form_AltUsuarios(JFrame parent, Usuario userToEdit) {
        super(parent, "Admin: Gestión de Usuario", true); // Diálogo modal (true)
        initComponents(); // Inicializa los componentes visuales

        this.usuarioController = new UsuarioController(); // Instancia del controlador de usuarios
        this.userToEdit = userToEdit;

        addEventHandlers();
        populateForm();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtApellido = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtUsuario1 = new javax.swing.JTextField();
        cbroles = new javax.swing.JComboBox<>();
        txtcorreo = new javax.swing.JTextField();
        jPasswordFieldB = new javax.swing.JPasswordField();
        btnMostrar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblCreacion = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios - Crear");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(51, 45, 86));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtApellido.setBackground(new java.awt.Color(51, 45, 86));
        txtApellido.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        txtApellido.setForeground(new java.awt.Color(255, 255, 255));
        txtApellido.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Apellido Paterno", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 260, 70));

        txtNombre.setBackground(new java.awt.Color(51, 45, 86));
        txtNombre.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        txtNombre.setForeground(new java.awt.Color(255, 255, 255));
        txtNombre.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nombre", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 260, 70));

        txtUsuario1.setBackground(new java.awt.Color(51, 45, 86));
        txtUsuario1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        txtUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        txtUsuario1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuario", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 100, 260, 60));

        cbroles.setBackground(new java.awt.Color(0, 0, 153));
        cbroles.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        cbroles.setForeground(new java.awt.Color(255, 255, 255));
        cbroles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rol", "Empleado", "Jefe_Abastecimiento", " " }));
        cbroles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.ABOVE_BOTTOM, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(cbroles, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 120, 260, 40));

        txtcorreo.setBackground(new java.awt.Color(51, 45, 86));
        txtcorreo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        txtcorreo.setForeground(new java.awt.Color(255, 255, 255));
        txtcorreo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Correo", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        txtcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcorreoActionPerformed(evt);
            }
        });
        jPanel1.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, 260, 60));

        jPasswordFieldB.setBackground(new java.awt.Color(51, 45, 86));
        jPasswordFieldB.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        jPasswordFieldB.setForeground(new java.awt.Color(255, 255, 255));
        jPasswordFieldB.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contraseña", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Microsoft PhagsPa", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jPasswordFieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 260, 60));

        btnMostrar.setBackground(new java.awt.Color(61, 144, 215));
        btnMostrar.setForeground(new java.awt.Color(61, 144, 215));
        btnMostrar.setText("⟳");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 30, 30));

        btnLimpiar.setBackground(new java.awt.Color(67, 0, 255));
        btnLimpiar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnLimpiar.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiar.setText("Limpiar");
        btnLimpiar.setBorder(null);
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 80, 30));

        btnGuardar1.setBackground(new java.awt.Color(255, 214, 102));
        btnGuardar1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnGuardar1.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar1.setText("Guardar");
        btnGuardar1.setBorder(null);
        btnGuardar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 260, 80, 30));

        btnCerrar.setBackground(new java.awt.Color(255, 0, 0));
        btnCerrar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("Cerrar");
        btnCerrar.setBorder(null);
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 80, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 680, 350));

        jPanel2.setBackground(new java.awt.Color(32, 87, 129));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreacion.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        lblCreacion.setForeground(new java.awt.Color(255, 255, 255));
        lblCreacion.setText("CREACIÓN DE NUEVO USUARIO");
        jPanel2.add(lblCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 580, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 70));

        setSize(new java.awt.Dimension(690, 427));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void addEventHandlers() {
        btnGuardar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnLimpiar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMostrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
    }

    private void populateForm() {
        if (userToEdit != null) {
            lblCreacion.setText("Edición de Usuario");
            txtNombre.setText(userToEdit.getNombre());
            txtApellido.setText(userToEdit.getApellido());
            txtUsuario1.setText(userToEdit.getUsuario());
            txtcorreo.setText(userToEdit.getCorreo());
            // No seteamos la contraseña por seguridad
            cbroles.setSelectedItem(userToEdit.getRol());
        }
    }

    public boolean isSuccess() {
        return successOperation;
    }

    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario1.setText("");
        txtcorreo.setText("");
        cbroles.setSelectedIndex(0);

        jPasswordFieldB.setText("");

    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose(); // Cierra esta ventana (el JDialog)

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String usuario = txtUsuario1.getText();
        String clave = new String(jPasswordFieldB.getPassword());
        String correo = txtcorreo.getText();
        String rol = (String) cbroles.getSelectedItem();

         // Validar campos vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || clave.isEmpty() || correo.isEmpty()) {
            Mensajes.mostrarError("Todos los campos son obligatorios");
            return;
        }
       // Validar correo Gmail
        if (!correo.endsWith("@gmail.com")) {
            Mensajes.mostrarAdvertencia("El correo debe ser una cuenta Gmail válida");
            return;
        }

        // Validar seguridad de la contraseña
        if (clave.length() < 8 || !clave.matches(".*[!@#$%^&*()_+=<>?/{}\\[\\]-].*")) {
            Mensajes.mostrarAdvertencia("La contraseña debe tener al menos 8 caracteres y un símbolo (por ejemplo: !, @, #, etc.)");
            return;
        }

        UsuarioController usuarioController = new UsuarioController();
        if (usuarioController.buscarPorUsuario(usuario) != null || usuarioController.buscarPorCorreo(correo) != null) {
            Mensajes.mostrarAdvertencia("Ya existe un usuario o correo registrado");
            return;
        }

        Usuario nuevo;
        if (rol.equals("Empleado")) {
            nuevo = new Empleado(nombre, apellido, usuario, clave, correo, rol);
        } else {
            nuevo = new JefeDeAbastecimiento(nombre, apellido, usuario, clave, correo, rol);
        }

        usuarioController.registrarUsuario(nuevo);
        Mensajes.mostrarInfo("Usuario registrado exitosamente");
        successOperation = true;
        limpiarCampos(); // limpia los campos del formulario
        // actualizarTabla();  eliminado porque no hay tabla aquí


    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        if (jPasswordFieldB.getEchoChar() == '*') {

            jPasswordFieldB.setEchoChar((char) 0);
        } else {

            jPasswordFieldB.setEchoChar('*');
        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void txtcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcorreoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_AltUsuarios dialog = new form_AltUsuarios(new javax.swing.JFrame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cbroles;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordFieldB;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario1;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
