package Ejercicio01;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User0
 */
public class form_RegistroAdmin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public form_RegistroAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();
        lblSignUpAdmin = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        lblApellido = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblcorreo = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        lblcontrasena = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        cbroles = new javax.swing.JComboBox<>();
        btnRegistrar = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        btnBackLog = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro Admin");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setToolTipText("");
        bg.setOpaque(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSignUpAdmin.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        lblSignUpAdmin.setForeground(new java.awt.Color(0, 48, 146));
        lblSignUpAdmin.setText("Sign Up Admin");
        bg.add(lblSignUpAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 290, 60));

        jLayeredPane1.setBackground(new java.awt.Color(0, 48, 146));
        jLayeredPane1.setOpaque(true);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        bg.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 0, 340, 640));

        lblApellido.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        lblApellido.setForeground(new java.awt.Color(102, 102, 102));
        lblApellido.setText("Apellido Paterno");
        bg.add(lblApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 130, -1));

        lblNombre.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        lblNombre.setForeground(new java.awt.Color(102, 102, 102));
        lblNombre.setText("Nombre");
        bg.add(lblNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, 20));

        lblcorreo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        lblcorreo.setForeground(new java.awt.Color(102, 102, 102));
        lblcorreo.setText("Correo");
        bg.add(lblcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 100, 20));

        txtUsuario.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        txtUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        bg.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 210, 30));

        txtNombre.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        txtNombre.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        bg.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 210, 30));

        txtApellido.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        txtApellido.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        bg.add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 210, 30));

        txtcorreo.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 12)); // NOI18N
        txtcorreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        bg.add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 210, 30));

        lblcontrasena.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        lblcontrasena.setForeground(new java.awt.Color(102, 102, 102));
        lblcontrasena.setText("Contraseña");
        bg.add(lblcontrasena, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 100, 20));

        lblUsuario.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(102, 102, 102));
        lblUsuario.setText("Usuario");
        bg.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 100, 20));

        cbroles.setBackground(new java.awt.Color(204, 255, 255));
        cbroles.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbroles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", " " }));
        cbroles.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Roles", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Microsoft PhagsPa", 0, 12))); // NOI18N
        bg.add(cbroles, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 210, 60));

        btnRegistrar.setBackground(new java.awt.Color(0, 48, 146));
        btnRegistrar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnRegistrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        bg.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 210, 30));

        jPasswordField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        bg.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 210, 40));

        btnBackLog.setBackground(new java.awt.Color(0, 48, 146));
        btnBackLog.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnBackLog.setForeground(new java.awt.Color(255, 255, 255));
        btnBackLog.setText("Volver al Login");
        btnBackLog.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnBackLog.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBackLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackLogActionPerformed(evt);
            }
        });
        bg.add(btnBackLog, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 560, 210, 30));

        btnMostrar.setBackground(new java.awt.Color(0, 48, 146));
        btnMostrar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnMostrar.setForeground(new java.awt.Color(255, 255, 255));
        btnMostrar.setText("◕◕");
        btnMostrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnMostrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        bg.add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 40, 40));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 650));

        setSize(new java.awt.Dimension(691, 644));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void btnBackLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackLogActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_RegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_RegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_RegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_RegistroAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_RegistroAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    private javax.swing.JButton btnBackLog;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cbroles;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel lblApellido;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblSignUpAdmin;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblcontrasena;
    private javax.swing.JLabel lblcorreo;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
