/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.vista;

import proyecto.controlador.UsuarioController;
import proyecto.modelo.Administrador;
import proyecto.modelo.Empleado;
import proyecto.modelo.JefeDeAbastecimiento;
import proyecto.modelo.Usuario; // Agregado: Importar la clase Usuario
import proyecto.util.Mensajes;

import javax.swing.JDialog; // Importante: Extiende de JDialog
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import proyecto.controlador.LoginController;

/**
 *
 * @author User0
 */
public class form_AltUsuarios extends javax.swing.JDialog {

    private UsuarioController usuarioController;
    private Usuario userToEdit; // Usuario que se está editando (null si es nuevo)
    private boolean successOperation = false;

    /**
     * Creates new form NewJDialog
     */
    public form_AltUsuarios(JFrame parent, Usuario userToEdit) {
        super(parent, "Admin: Gestión de Usuario", true); // Diálogo modal (true)
        initComponents(); // Inicializa los componentes visuales

        this.usuarioController = new UsuarioController(); // Instancia del controlador de usuarios
        this.userToEdit = userToEdit;

        addEventHandlers(); // Asigna los ActionListeners
        populateForm(); // Rellena el formulario si es edición

        // Asegúrate que los campos de token estén ocultos al inicio, si no son Admin.
        // Se usan los nombres de variable de tu diseñador: jTextField1 y jLabel1.
        jTextField1.setVisible(false); // Ocultar por defecto (controlado por Listener)
        lblCreacion.setVisible(false);     // Ocultar por defecto (controlado por Listener)
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCreacion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        txtcorreo = new javax.swing.JTextField();
        jPasswordFieldB = new javax.swing.JPasswordField();
        txtUsuario1 = new javax.swing.JTextField();
        cbroles = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnLimpiar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btnGuardar1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCreacion.setText("Creación de un nuevo Usuario");
        getContentPane().add(lblCreacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 240, 40));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 210, 30));
        getContentPane().add(txtApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 210, 30));
        getContentPane().add(txtcorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 210, 30));

        jPasswordFieldB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 48, 146)));
        getContentPane().add(jPasswordFieldB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 210, 40));
        getContentPane().add(txtUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, 210, 30));

        cbroles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Empleado", "Jefe_Abastecimiento", " " }));
        getContentPane().add(cbroles, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 100, -1));

        jLabel2.setText("Correo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        jLabel3.setText("Nombre");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        jLabel4.setText("Apellido Paterno");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 130, 100, -1));

        lblUsuario.setText("Usuario");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 60, -1));

        jLabel6.setText("Contraseña");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, -1, -1));

        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, -1, 40));

        btnGuardar1.setText("Guardar");
        btnGuardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 260, -1, -1));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 350, -1, -1));

        jTextField1.setText("jTextField1");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void addEventHandlers() {
        btnGuardar1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnGuardar1ActionPerformed(evt);
            }
        });

        btnLimpiar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnCerrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        btnMostrar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
    }

    private void populateForm() {
        if (userToEdit != null) {
            lblCreacion.setText("Edición de Usuario");
            txtNombre.setText(userToEdit.getNombre());
            txtApellido.setText(userToEdit.getApellido());
            txtUsuario1.setText(userToEdit.getUsuario());
            txtcorreo.setText(userToEdit.getCorreo());
            // No seteamos la contraseña por seguridad
            cbroles.setSelectedItem(userToEdit.getRol());
        }
    }
    public boolean isSuccess(){return successOperation;}
    
    
    private void limpiarCampos() {
        txtNombre.setText("");
        txtApellido.setText("");
        txtUsuario1.setText("");
        txtcorreo.setText("");
        cbroles.setSelectedIndex(0);
        String clave = new String(jPasswordFieldB.getPassword());
        
        
    }
    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose(); // Cierra esta ventana (el JDialog)

    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnGuardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardar1ActionPerformed
        String nombre = txtNombre.getText();
        String apellido = txtApellido.getText();
        String usuario = txtUsuario1.getText();
        String clave = new String(jPasswordFieldB.getPassword());
        String correo = txtcorreo.getText();
        String rol = (String) cbroles.getSelectedItem();
       
// Validar campos vacíos
        if (nombre.isEmpty() || apellido.isEmpty() || usuario.isEmpty() || clave.isEmpty() || correo.isEmpty()) {
            Mensajes.mostrarError("Todos los campos son obligatorios");
            return;
        }
// Validar correo Gmail
        if (!correo.endsWith("@gmail.com")) {
            Mensajes.mostrarAdvertencia("El correo debe ser una cuenta Gmail válida");
            return;
        }

// Validar seguridad de la contraseña
        if (clave.length() < 8 || !clave.matches(".*[!@#$%^&*()_+=<>?/{}\\[\\]-].*")) {
            Mensajes.mostrarAdvertencia("La contraseña debe tener al menos 8 caracteres y un símbolo (por ejemplo: !, @, #, etc.)");
            return;
        }

        UsuarioController usuarioController = new UsuarioController();
        if (usuarioController.buscarPorUsuario(usuario) != null || usuarioController.buscarPorCorreo(correo) != null) {
            Mensajes.mostrarAdvertencia("Ya existe un usuario o correo registrado");
            return;
        }

        Usuario nuevo;
        if (rol.equals("Empleado")) {
            nuevo = new Empleado(nombre, apellido, usuario, clave, correo, rol);
        } else {
            nuevo = new JefeDeAbastecimiento(nombre, apellido, usuario, clave, correo, rol);
        }

        usuarioController.registrarUsuario(nuevo);
        Mensajes.mostrarInfo("Usuario registrado exitosamente");
        successOperation = true;
        limpiarCampos(); // limpia los campos del formulario
        // actualizarTabla();  eliminado porque no hay tabla aquí


    }//GEN-LAST:event_btnGuardar1ActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        if (jPasswordFieldB.getEchoChar() == '•') {
            jPasswordFieldB.setEchoChar((char) 0); // Mostrar texto

        } else {

            jPasswordFieldB.setEchoChar('•'); // Ocultar texto

        }
    }//GEN-LAST:event_btnMostrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_AltUsuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                form_AltUsuarios dialog = new form_AltUsuarios(new javax.swing.JFrame(), null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnGuardar1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JComboBox<String> cbroles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordFieldB;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCreacion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtUsuario1;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
