package proyecto.vista;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import proyecto.controlador.UsuarioController;
import proyecto.modelo.Usuario;
import proyecto.util.Mensajes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author User0
 */
public class form_SistemaAdmin extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public form_SistemaAdmin() {
        initComponents();
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Nombre", "Apellido", "Usuario", "Correo", "Rol", "contraseña"}
        );
        tableAdmin.setModel(modelo);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JLayeredPane();
        lblSistemaAdminstrador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAdmin = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSalirAdmin = new javax.swing.JButton();
        btnBorrarUsuario = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCrearNuevoUsuario1 = new javax.swing.JButton();
        btnGenerarTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de Admin");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusable(false);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setToolTipText("");
        bg.setOpaque(true);
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSistemaAdminstrador.setFont(new java.awt.Font("Yu Gothic", 1, 36)); // NOI18N
        lblSistemaAdminstrador.setForeground(new java.awt.Color(0, 48, 146));
        lblSistemaAdminstrador.setText("Sistema Administrador de Usuarios");
        bg.add(lblSistemaAdminstrador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 660, 60));

        tableAdmin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableAdmin);

        bg.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 660, 440));

        jPanel1.setBackground(new java.awt.Color(54, 116, 181));

        btnSalirAdmin.setBackground(new java.awt.Color(203, 4, 4));
        btnSalirAdmin.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnSalirAdmin.setForeground(new java.awt.Color(255, 255, 255));
        btnSalirAdmin.setText("Salir de la Cuenta");
        btnSalirAdmin.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0), new java.awt.Color(153, 0, 0)));
        btnSalirAdmin.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSalirAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAdminActionPerformed(evt);
            }
        });

        btnBorrarUsuario.setBackground(new java.awt.Color(0, 48, 146));
        btnBorrarUsuario.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnBorrarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnBorrarUsuario.setText("Borrar Usuario");
        btnBorrarUsuario.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnBorrarUsuario.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarUsuarioActionPerformed(evt);
            }
        });

        btnActualizar.setBackground(new java.awt.Color(0, 48, 146));
        btnActualizar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizar.setText("Actualizar Información");
        btnActualizar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnCrearNuevoUsuario1.setBackground(new java.awt.Color(0, 48, 146));
        btnCrearNuevoUsuario1.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnCrearNuevoUsuario1.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearNuevoUsuario1.setText("Crear Nuevo Usuario");
        btnCrearNuevoUsuario1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnCrearNuevoUsuario1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCrearNuevoUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearNuevoUsuario1ActionPerformed(evt);
            }
        });

        btnGenerarTxt.setBackground(new java.awt.Color(0, 48, 146));
        btnGenerarTxt.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnGenerarTxt.setForeground(new java.awt.Color(255, 255, 255));
        btnGenerarTxt.setText("Generar txt");
        btnGenerarTxt.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 153), new java.awt.Color(102, 102, 255), new java.awt.Color(0, 0, 51)));
        btnGenerarTxt.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnGenerarTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(14, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSalirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCrearNuevoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnBorrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnGenerarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(btnCrearNuevoUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBorrarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGenerarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 213, Short.MAX_VALUE)
                .addComponent(btnSalirAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 0, 170, 620));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 620));

        setSize(new java.awt.Dimension(866, 624));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAdminActionPerformed
        form_login login = new form_login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSalirAdminActionPerformed
    private void actualizarTabla() {
        DefaultTableModel modelo = (DefaultTableModel) tableAdmin.getModel();
        modelo.setRowCount(0); // Limpia las filas actuales de la tabla

        UsuarioController usuarioController = new UsuarioController();
        List<Usuario> usuarios = usuarioController.listarUsuarios();

        for (Usuario u : usuarios) {
            if (!u.getRol().equalsIgnoreCase("Admin")) {
                modelo.addRow(new Object[]{
                    u.getNombre(),
                    u.getApellido(),
                    u.getUsuario(),
                    u.getCorreo(),
                    u.getRol(),
                    u.getClave()
                });
            }
        }
    }
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        actualizarTabla();
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarUsuarioActionPerformed
        int fila = tableAdmin.getSelectedRow();
        UsuarioController usuarioController = new UsuarioController();

        if (fila >= 0) {
            String usuario = tableAdmin.getValueAt(fila, 2).toString();

            int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                    this,
                    "¿Está seguro que desea eliminar al usuario \"" + usuario + "\"?",
                    "Confirmar eliminación",
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
                usuarioController.eliminarUsuario(usuario);
                Mensajes.mostrarInfo("Usuario eliminado correctamente");
                actualizarTabla();
            }

        } else {
            Mensajes.mostrarAdvertencia("Seleccione un usuario para eliminar");
        }
    }//GEN-LAST:event_btnBorrarUsuarioActionPerformed

    private void btnCrearNuevoUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearNuevoUsuario1ActionPerformed
        form_AltUsuarios altUsuarios = new form_AltUsuarios();
        altUsuarios.setVisible(true);
        // ¡NO pongas this.dispose(); ni this.setVisible(false);

    }//GEN-LAST:event_btnCrearNuevoUsuario1ActionPerformed

    private void generarArchivoTxt() {
        try {
            FileWriter writer = new FileWriter("usuarios.txt");
            BufferedWriter bufferedWriter = new BufferedWriter(writer);

            // Escribir encabezados
            for (int i = 0; i < tableAdmin.getColumnCount(); i++) {
                bufferedWriter.write(tableAdmin.getColumnName(i) + "\t");
            }
            bufferedWriter.newLine();

            // Escribir datos fila por fila
            for (int i = 0; i < tableAdmin.getRowCount(); i++) {
                for (int j = 0; j < tableAdmin.getColumnCount(); j++) {
                    Object valor = tableAdmin.getValueAt(i, j);
                    bufferedWriter.write((valor != null ? valor.toString() : "") + "\t");
                }
                bufferedWriter.newLine();
            }

            bufferedWriter.close();
            Mensajes.mostrarInfo("Archivo 'usuarios.txt' generado exitosamente.");
        } catch (IOException e) {
            Mensajes.mostrarError("Error al generar archivo: " + e.getMessage());
        }
    }


    private void btnGenerarTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarTxtActionPerformed
        generarArchivoTxt();
    }//GEN-LAST:event_btnGenerarTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_SistemaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_SistemaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLayeredPane bg;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrarUsuario;
    private javax.swing.JButton btnCrearNuevoUsuario1;
    private javax.swing.JButton btnGenerarTxt;
    private javax.swing.JButton btnSalirAdmin;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSistemaAdminstrador;
    private javax.swing.JTable tableAdmin;
    // End of variables declaration//GEN-END:variables

}
