/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package proyecto.vista;

import com.lowagie.text.Chunk;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.PageSize;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfDocument;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import java.text.SimpleDateFormat;
import java.util.Date;
import com.lowagie.text.pdf.PdfReader;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.parser.PdfTextExtractor;
import java.awt.Color;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User0
 */
public class Panel_ReporteVentasAdmin extends javax.swing.JDialog {

    /**
     * Creates new form Panel_ReporteVentasAdmin
     */
    public Panel_ReporteVentasAdmin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLogin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogin1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblValorStock1 = new javax.swing.JLabel();
        lblValorStock2 = new javax.swing.JLabel();
        lblValorStock3 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jDateChooserHasta = new com.toedter.calendar.JDateChooser();
        btnGenerarReporte = new javax.swing.JButton();
        lblValorStock4 = new javax.swing.JLabel();
        lblValorStock5 = new javax.swing.JLabel();
        jDateChooserDesde = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVentasResumen = new javax.swing.JTable();

        lblLogin.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 48, 146));
        lblLogin.setText("LOGIN");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reporte de Ventas Totales");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(54, 116, 181));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 26, 110));
        jPanel1.setForeground(new java.awt.Color(92, 114, 133));

        lblLogin1.setFont(new java.awt.Font("Yu Gothic", 1, 40)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin1.setText("REPORTE DE VENTAS TOTALES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 816, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addComponent(lblLogin1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 860, 80));

        jPanel3.setBackground(new java.awt.Color(215, 215, 215));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.Color.darkGray));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblValorStock1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorStock1.setForeground(new java.awt.Color(51, 51, 51));
        lblValorStock1.setText("Stock: ");
        jPanel3.add(lblValorStock1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, -1));

        lblValorStock2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorStock2.setForeground(new java.awt.Color(51, 51, 51));
        lblValorStock2.setText("Stock: ");
        jPanel3.add(lblValorStock2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 70, -1));

        lblValorStock3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorStock3.setForeground(new java.awt.Color(51, 51, 51));
        lblValorStock3.setText("Hasta:");
        jPanel3.add(lblValorStock3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 180, -1));

        btnFiltrar.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });
        jPanel3.add(btnFiltrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 190, 38));

        jDateChooserHasta.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.add(jDateChooserHasta, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 190, -1));

        btnGenerarReporte.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        btnGenerarReporte.setText("Generar Reporte PDF");
        btnGenerarReporte.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(221, 168, 83), null, null));
        btnGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReporteActionPerformed(evt);
            }
        });
        jPanel3.add(btnGenerarReporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 190, 30));

        lblValorStock4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorStock4.setForeground(new java.awt.Color(51, 51, 51));
        lblValorStock4.setText("Selecciona una fecha: ");
        jPanel3.add(lblValorStock4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 200, -1));

        lblValorStock5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValorStock5.setForeground(new java.awt.Color(51, 51, 51));
        lblValorStock5.setText("Desde:");
        jPanel3.add(lblValorStock5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 180, -1));
        jPanel3.add(jDateChooserDesde, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 190, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 220, 290));

        tablaVentasResumen.setFont(new java.awt.Font("Microsoft PhagsPa", 0, 14)); // NOI18N
        tablaVentasResumen.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha de Venta", "Cliente Asociado", "Total de ventas"
            }
        ));
        jScrollPane1.setViewportView(tablaVentasResumen);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 110, 570, 240));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, -10, 870, 420));

        setSize(new java.awt.Dimension(869, 417));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

        Date desde = jDateChooserDesde.getDate();
        Date hasta = jDateChooserHasta.getDate();

        if (desde == null || hasta == null) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar ambas fechas.");
            return;
        }

        File carpetaFacturas = new File("Facturas/");
        if (!carpetaFacturas.exists() || !carpetaFacturas.isDirectory()) {
            JOptionPane.showMessageDialog(this, "La carpeta 'Facturas/' no existe.");
            return;
        }

        File[] archivosPDF = carpetaFacturas.listFiles((dir, name) -> name.toLowerCase().endsWith(".pdf"));

        DefaultTableModel modelo = (DefaultTableModel) tablaVentasResumen.getModel();
        modelo.setRowCount(0); // Limpiar tabla

        double totalAcumulado = 0;

        try {
            for (File archivo : archivosPDF) {
                PdfReader reader = new PdfReader(archivo.getAbsolutePath());
                PdfTextExtractor extractor = new PdfTextExtractor(reader);
                String contenido = extractor.getTextFromPage(1); // Solo primera página
                reader.close();

                String[] lineas = contenido.split("\n");
                String fechaStr = "";
                String cliente = "General";
                String montoStr = "";

                for (String linea : lineas) {
                    if (linea.startsWith("Fecha:")) {
                        fechaStr = linea.replace("Fecha:", "").trim();
                    } else if (linea.startsWith("Total a pagar")) { // ← CORREGIDO
                        montoStr = linea.replace("Total a pagar :", "").trim();
                    } else if (linea.startsWith("Cliente:")) {
                        cliente = linea.replace("Cliente:", "").trim();
                    }
                }

                if (!fechaStr.isEmpty() && !montoStr.isEmpty()) {
                    Date fechaFactura = sdf.parse(fechaStr);
                    if (!fechaFactura.before(desde) && !fechaFactura.after(hasta)) {
                        modelo.addRow(new Object[]{fechaStr, cliente, montoStr});
                        totalAcumulado += Double.parseDouble(montoStr);
                    }
                }
            }

            if (modelo.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "No se encontraron facturas en el rango de fechas.");
            } else {
                JOptionPane.showMessageDialog(this, "✅ Total acumulado: S/ " + String.format("%.2f", totalAcumulado));
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al leer las facturas: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btnFiltrarActionPerformed

    private void btnGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReporteActionPerformed
        try {
            // 1. Crear carpeta si no existe
            File carpeta = new File("ReporteDeVentasGenerados");
            if (!carpeta.exists()) {
                carpeta.mkdirs();
            }

            // 2. Preparar PDF
            String nombreArchivo = "ReporteDeVentasGenerados/Reporte_" + System.currentTimeMillis() + ".pdf";
            Document doc = new Document(PageSize.A4, 40, 40, 40, 40);
            PdfWriter.getInstance(doc, new FileOutputStream(nombreArchivo));
            doc.open();

            // 3. Fuentes
            Font tituloFont = new Font(Font.HELVETICA, 18, Font.BOLD, Color.BLUE);
            Font encabezadoFont = new Font(Font.HELVETICA, 12, Font.BOLD, Color.BLACK);
            Font normalFont = new Font(Font.HELVETICA, 11, Font.NORMAL, Color.BLACK);

            // 4. Título
            Paragraph titulo = new Paragraph("REPORTE DE VENTAS TOTALES", tituloFont);
            titulo.setAlignment(Element.ALIGN_CENTER);
            doc.add(titulo);

            doc.add(new Paragraph("Generado: " + new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date()), normalFont));
            doc.add(Chunk.NEWLINE);

            // 5. Tabla PDF
            PdfPTable tabla = new PdfPTable(3); // 3 columnas
            tabla.setWidthPercentage(100);
            tabla.setWidths(new int[]{35, 35, 30});
            tabla.addCell(new PdfPCell(new Phrase("Fecha de Venta", encabezadoFont)));
            tabla.addCell(new PdfPCell(new Phrase("Cliente Asociado", encabezadoFont)));
            tabla.addCell(new PdfPCell(new Phrase("Monto de la Venta (S/)", encabezadoFont)));

            double totalAcumulado = 0.0;
            DefaultTableModel modelo = (DefaultTableModel) tablaVentasResumen.getModel();

            for (int i = 0; i < modelo.getRowCount(); i++) {
                String fecha = modelo.getValueAt(i, 0).toString();
                String cliente = modelo.getValueAt(i, 1).toString();
                String monto = modelo.getValueAt(i, 2).toString();

                tabla.addCell(new Phrase(fecha, normalFont));
                tabla.addCell(new Phrase(cliente, normalFont));
                tabla.addCell(new Phrase(monto, normalFont));

                try {
                    totalAcumulado += Double.parseDouble(monto);
                } catch (NumberFormatException e) {
                    // Si hay un valor inválido, lo ignora
                }
            }

            doc.add(tabla);
            doc.add(Chunk.NEWLINE);

            // 6. Total acumulado
            Paragraph total = new Paragraph("TOTAL ACUMULADO: S/ " + String.format("%.2f", totalAcumulado), encabezadoFont);
            total.setAlignment(Element.ALIGN_RIGHT);
            doc.add(total);

            doc.close();

            JOptionPane.showMessageDialog(this, "✅ Reporte generado correctamente:\n" + nombreArchivo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error al generar el reporte: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarReporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel_ReporteVentasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel_ReporteVentasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel_ReporteVentasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel_ReporteVentasAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Panel_ReporteVentasAdmin dialog = new Panel_ReporteVentasAdmin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGenerarReporte;
    private com.toedter.calendar.JDateChooser jDateChooserDesde;
    private com.toedter.calendar.JDateChooser jDateChooserHasta;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblValorStock1;
    private javax.swing.JLabel lblValorStock2;
    private javax.swing.JLabel lblValorStock3;
    private javax.swing.JLabel lblValorStock4;
    private javax.swing.JLabel lblValorStock5;
    private javax.swing.JTable tablaVentasResumen;
    // End of variables declaration//GEN-END:variables
}
